#!/bin/bash
GOFILES=$(ls *.go)
if [ -z "$GOFILES" ]; then
	echo not a go package
	exit 111
fi

# grab make.go and make executable: https://github.com/aerth/make.go/
env CGO_ENABLED=0 make.go -o pkg/ -all -v
RWD=$(pwd)
cd pkg && sha256sum * > ../SHA256.txt; cd $RWD;

# package each file in 'pkg' dir
for i in $(ls pkg); do
	echo Packaging $i; 
	mkdir -p $i; 
	cp pkg/$i $i/$i; 
	cp README.md $i/; 
	cp LICENSE $i/; 
	cp -avx docs $i/; 
	mkdir -p $i/src; 
	cp *.go $i/src/; 
	cp SHA256.txt $i/;
	zip -r $i.zip $i/;
	tar czf $i.tar.gz $i; 
	rm -rvf $i;
done